Repository ember-fastboot/fastboot, pull requests merged in 2020-10, with the labels that each got.

#277 Restore result finalization in resilient mode
  src/ember-app.js
  test/fastboot-test.js
Labels: bug

#279 Migrate to GitHub Actions for CI.
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#278 Update release setup.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#281 Ensure extraneous files are not published.
  package.json
  yarn.lock
Labels: bug

#282 Remove node version in Readme
  README.md
Labels: documentation
